platform :ios, '9.0'

target 'ZJCrossCppDemo' do
#  use_frameworks!

   pod 'ReactiveObjC', '~> 3.1.1'
   pod 'Masonry', '~>1.1.0'
   pod 'ZJBaseUtils', :path =>'/Users/lzj/Desktop/Project/ZJBaseUtils_iOS/ZJBaseUtils.podspec'
   pod 'ZJCrossCpp',  :path =>'../ZJCrossCpp.podspec'
   
end

